### ISSUE TITLE
AttributeError: module 'sketchgraphs.data' has no attribute 'ConstructionSequence'

### ISSUE THREAD

**Issue by KLMN2001** [PrincetonLIPS/vitruvion#7]
Thanks for your contribution, this is an inspiring work! But when I try to run training and evaluation in my own conda environment, I run into some problems that I want you to help me.
As we konw, _sketchgraphs.data_ is mentioned in many programs, for example in the _/vitruvion/img2cad/constraint_data.py_ there are `import _sketchgraphs.data as datalib` and `from sketchgraphs.data import flat_array`, but here is no folder named _data_ in the vitruvion/sketchgraphs/directory in this github project. 
This seems to be resolved by downloading the file in SketchGraphs, and it is true for some parts of the code, but there seems to be no ConstructionSequence, and I would like to know how to find or retrieve this file, thank you for your focus!
```
/vitruvion/img2cad/constraint_data.py
import sketchgraphs.data as datalib
def tokenize_constraints(seq: datalib.ConstructionSequence, gather_idxs: Sequence[int], max_length: Optional[int]=None):
```
When I run `python -m img2cad.evaluation.evaluate_constraints checkpoint_path=models/constraints.ckpt sequence_path=data/sg_filtered_unique.npy`, I will get
```
File "****/code/vitruvion/img2cad/constraint_data.py", line 67, in <module>
    def tokenize_constraints(seq: datalib.ConstructionSequence, gather_idxs: Sequence[int], max_length: Optional[int]=None):
AttributeError: module 'sketchgraphs.data' has no attribute 'ConstructionSequence'
```

**Comment by k-cv** [comment]
Is this problem alreday solved?
I encountered same error.

**Comment by k-cv** [comment]
I will write in Japanese
解決方法がわかったのでお知らせします。
https://princetonlips.github.io/SketchGraphs/_autosummary/sketchgraphs.data.html
こちらを参照した時、sketchgraphs.dataに存在するattibuteは5つしかありません。
その中で最も適当なものは`sketchgraphs.data.sequence`と考えられます。
そこで、`ConstructionSequence`を`sequence`に書き換えたところ、正常に動作しました。
お試しください。
I hope this comment to be useful for you.
